// apps/mfe-blog/components/ReadingProgress.vue
<script setup lang="ts">
const progress = ref(0)

function update() {
  const scrollTop = window.scrollY
  const docHeight = document.documentElement.scrollHeight - window.innerHeight
  progress.value = docHeight > 0 ? Math.min(100, (scrollTop / docHeight) * 100) : 0
}

onMounted(() => window.addEventListener('scroll', update, { passive: true }))
onUnmounted(() => window.removeEventListener('scroll', update))
</script>

<template>
  <div class="track" aria-hidden="true">
    <div class="bar" :style="{ width: `${progress}%` }" />
  </div>
</template>

<style scoped>
.track {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  height: 2px;
  z-index: 100;
  background: var(--color-border);
}

.bar {
  height: 100%;
  background: var(--color-teal);
  transition: width 0.08s linear;
}
</style>

// packages/ui/src/components/ReadingProgress/index.tsx
import { useEffect, useState } from 'react'

export function ReadingProgress() {
  const [progress, setProgress] = useState(0)

  useEffect(() => {
    const update = () => {
      const { scrollTop, scrollHeight, clientHeight } = document.documentElement
      const total = scrollHeight - clientHeight
      setProgress(total > 0 ? (scrollTop / total) * 100 : 0)
    }
    window.addEventListener('scroll', update, { passive: true })
    return () => window.removeEventListener('scroll', update)
  }, [])

  return (
    <div style={{ position: 'fixed', top: 0, left: 0, right: 0, height: '2px', background: 'var(--color-border)', zIndex: 100 }}>
      <div style={{ height: '100%', width: `${progress}%`, background: 'var(--color-teal)', transition: 'width 0.1s linear' }} />
    </div>
  )
}
